add_newline = false

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$character"""

right_format = """
$cmd_duration\
${custom.openshift}\
$java\
$jobs\
${custom.yadm}"""

[cmd_duration]
format = " [ $duration]($style)"
style = "bright-black"

[directory]
truncation_length = 4
fish_style_pwd_dir_length = 2
truncate_to_repo = false
read_only = ""
style = "grey"

[git_branch]
symbol = ""
style = "#f1502f"
format = "[$symbol]($style)$branch "
only_attached = true

[git_commit]
only_detached = true
format = "[]($style)$hash$tag "
style = "#f1502f"
tag_disabled = false
tag_symbol = "  "

[git_status]
format = '([$all_status$ahead_behind]($style) )'
conflicted = "☹︎$count"
ahead = "⇡$count"
behind = "⇣$count"
diverged = "⇡$ahead_count⇣$behind_count"
untracked = "?$count"
modified = '+$count'
staged = "•$count"
renamed = "»$count"
deleted = "✘$count"
stashed = "⚑$count"
style = "white"

[hostname]
format = "@[$hostname]($style):"

[java]
version_format = "${major}.${minor}"
symbol = ""
format = " [${symbol} (${version})]($style)"
style = "#5382a1"

[jobs]
symbol = " "

[username]
format = "[$user]($style)"

[custom.yadm]
when = "command yadm --no-optional-locks status --untracked-files=no --branch --porcelain=2 2>/dev/null | string match --regex --quiet --invert '(^# branch.oid .\\w+$|^# branch.head \\w+$|^# branch.upstream .+$|^# branch.ab \\+0 -0$)'"
description = "Uncommited or unpushed changes in YADM managed dotfiles"
symbol = " "

[custom.openshift]
when = "oc project -q"
description = "The current openshift project"
command = "oc project -q"
symbol = "⎈ "
style = "#326ce5"
format = ' [$symbol]($style)$output'

