add_newline = false

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
\n$character"""

right_format = """
$cmd_duration\
$java\
$jobs\
$shlvl"""

[cmd_duration]
format = " [ $duration]($style)"
style = "bright-black"

[directory]
truncation_length = 10
fish_style_pwd_dir_length = 3
truncate_to_repo = false
read_only = ""
style = "grey"

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
only_attached = true
style = "purple"

[git_commit]
only_detached = true
format = "[ $hash$tag]($style) "
tag_disabled = false
tag_symbol = "  "
style = "purple"

[git_status]
format = '([$all_status$ahead_behind]($style) )'
conflicted = "☹︎$count"
ahead = "⇡$count"
behind = "⇣$count"
diverged = "⇡$ahead_count⇣$behind_count"
untracked = "?$count"
modified = '+$count'
staged = "•$count"
renamed = "»$count"
deleted = "✘$count"
stashed = "⚑$count"
style = "blue"

[hostname]
format = "[$hostname]($style):"

[java]
version_format = "${major}"
symbol = ""
format = " [${symbol} (${version})]($style)"
style = "#5382a1"

[jobs]
symbol = " 󰒓 "
style = "blue"

[username]
format = "[$user]($style)@"

[shlvl]
disabled = false
format = '⤷ $shlvl'
