palette = "catppuccin_frappe"
add_newline = false

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$character"""

right_format = """
$cmd_duration\
$java\
$jobs"""

[cmd_duration]
format = " [ $duration]($style)"
style = "bright-black"

[directory]
truncation_length = 4
fish_style_pwd_dir_length = 2
truncate_to_repo = false
read_only = ""
style = "grey"

[git_branch]
symbol = ""
style = "#f1502f"
format = "[$symbol]($style)$branch "
only_attached = true

[git_commit]
only_detached = true
format = "[]($style)$hash$tag "
style = "#f1502f"
tag_disabled = false
tag_symbol = "  "

[git_status]
format = '([$all_status$ahead_behind]($style) )'
conflicted = "☹︎$count"
ahead = "⇡$count"
behind = "⇣$count"
diverged = "⇡$ahead_count⇣$behind_count"
untracked = "?$count"
modified = '+$count'
staged = "•$count"
renamed = "»$count"
deleted = "✘$count"
stashed = "⚑$count"
style = "white"

[hostname]
format = "@[$hostname]($style):"

[java]
version_format = "${major}"
symbol = ""
format = " [${symbol} (${version})]($style)"
style = "#5382a1"

[jobs]
symbol = " 󰒓 "
style = "blue"

[username]
format = "[$user]($style)"

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"
